image: gitpod/workspace-full

# Commands to start on workspace startup
tasks:
  - init: cd .freeCodeCamp && npm run gitpod:ensure-tools
    command: code --install-extension ../.devcontainer/freeCodeCamp.freecodecamp-dark-vscode-theme-0.1.0.vsix && echo "PROMPT_COMMAND='>| /workspace/external-project/curriculum/.freecodecamp/.terminal-out.log && cat /workspace/external-project/curriculum/.freecodecamp/.temp.log >| /workspace/external-project/curriculum/.freecodecamp/.terminal-out.log && truncate -s 0 /workspace/external-project/curriculum/.freecodecamp/.temp.log; echo $PWD >> /workspace/external-project/curriculum/.freecodecamp/.cwd; history -a'" >> ~/.bashrc

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - https://github.com/ShaunSHamilton/courses-plus/raw/main/freecodecamp-courses-patch.vsix
